### ISSUE TITLE
声卡布局ID不能选择

### ISSUE THREAD

**Issue by mingwu** [JeoJay127/RapidEFI-Tool#25]
系统信息
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎8/‎21
操作系统版本	22631.4317
体验	Windows Feature Experience Pack 1000.22700.1041.0

下图的箭头所指都不能鼠标点击
![1728800844182](https://github.com/user-attachments/assets/9a446e0c-af9c-42a3-949f-5cfe02a6c005)

**Comment by JeoJay127** [comment]
操作问题，点击右下角 “确定”
