### ISSUE TITLE
开启resizable bar 后卡EB

### ISSUE THREAD

**Issue by dnegeL404** [JeoJay127/RapidEFI-Tool#26]
建议在Booter - Quirks中添加ResizeAppleGpuBars的切换选项。

**Comment by fatic** [comment]
No english version app

**Comment by chris6868** [comment]
我也是卡EB

**Comment by chris6868** [comment]
3.1.0不会卡，3.2.0会

**Comment by JeoJay127** [comment]
7代之后,工具3.1版本开始ResizeAppleGpuBars默认设置0（BIOS中Re-size Bar Support可以开启）

**Comment by JeoJay127** [comment]
> 3.1.0不会卡，3.2.0会

方便贴下具体配置？

**Comment by JeoJay127** [comment]
> 同样遇到了，resizable bar禁用，还是卡EB，什么原因

resizable bar的开启与禁用与EB没关系

你的情况具体得看配置，不过主要为以下两点可供参考(如果使用工具配置的EFI)：
1.intel 用户卡EB主要是booter选项
2.AMD用户主要是核心数不正确

**Comment by chris6868** [comment]
> > 3.1.0不会卡，3.2.0会
> 
> 方便贴下具体配置？
[3.1-config.txt](https://github.com/user-attachments/files/17751578/3.1-config.txt)
[3.2-config.txt](https://github.com/user-attachments/files/17751579/3.2-config.txt)
3.1config，是之前版本做的，3.2是最新版本做的

**Comment by chris6868** [comment]
3.2版本还有个bug，点了X-是，需要很久才能关闭窗口，有时候还会卡死关不掉

**Comment by JeoJay127** [comment]
> > > 3.1.0不会卡，3.2.0会
> > 
> > 
> > 方便贴下具体配置？
> > [3.1-config.txt](https://github.com/user-attachments/files/17751578/3.1-config.txt)
> > [3.2-config.txt](https://github.com/user-attachments/files/17751579/3.2-config.txt)
> > 3.1config，是之前版本做的，3.2是最新版本做的


大致看了下，你操作问题，3.2并非是最新做的，建议删了重新制作
